ALTER TABLE ai_settings
    ADD COLUMN IF NOT EXISTS service_profile VARCHAR(32) NOT NULL DEFAULT 'CONSULTATIVE',
    ADD COLUMN IF NOT EXISTS tone VARCHAR(32) NOT NULL DEFAULT 'WARM',
    ADD COLUMN IF NOT EXISTS formality VARCHAR(32) NOT NULL DEFAULT 'BALANCED',
    ADD COLUMN IF NOT EXISTS response_length VARCHAR(32) NOT NULL DEFAULT 'CONCISE',
    ADD COLUMN IF NOT EXISTS commercial_approach VARCHAR(32) NOT NULL DEFAULT 'DISCOVER_FIRST',
    ADD COLUMN IF NOT EXISTS custom_instructions TEXT,
    ADD COLUMN IF NOT EXISTS approved_examples TEXT,
    ADD COLUMN IF NOT EXISTS rejected_examples TEXT;
