ALTER TABLE lead
    ADD COLUMN IF NOT EXISTS summary VARCHAR(2000),
    ADD COLUMN IF NOT EXISTS intent VARCHAR(120),
    ADD COLUMN IF NOT EXISTS score INTEGER,
    ADD COLUMN IF NOT EXISTS next_action VARCHAR(500);
