spring.application.name=anysale-ingestion-gateway

# Porta
server.port=${SERVER_PORT:8083}

# HTTP -> lead-service
lead-service.base-url=${LEAD_SERVICE_BASE_URL:http://localhost:8080}
whatsapp.webhook.verify-token=${WHATSAPP_WEBHOOK_VERIFY_TOKEN:}
whatsapp.webhook.app-secret=${WHATSAPP_APP_SECRET:}

# Resilience4j (se estiver usando @Retry/@CircuitBreaker "leadClient")
resilience4j.retry.instances.leadClient.max-attempts=${LEAD_CLIENT_RETRY_MAX_ATTEMPTS:3}
resilience4j.retry.instances.leadClient.wait-duration=${LEAD_CLIENT_RETRY_WAIT_DURATION:300ms}
resilience4j.circuitbreaker.instances.leadClient.sliding-window-size=${LEAD_CLIENT_CB_SLIDING_WINDOW_SIZE:10}
resilience4j.circuitbreaker.instances.leadClient.failure-rate-threshold=${LEAD_CLIENT_CB_FAILURE_RATE_THRESHOLD:50}

# Actuator (se quiser expor também)
management.endpoints.web.exposure.include=health,info
