version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: pg-anysale
    environment:
      POSTGRES_DB: anysale
      POSTGRES_USER: anysale
      POSTGRES_PASSWORD: secret
    ports: ["5435:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]

  mongo:
    image: mongo:6
    container_name: mongo-anysale
    ports: ["27017:27017"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zk-anysale
    environment: { ZOOKEEPER_CLIENT_PORT: 2181 }
    ports: ["2181:2181"]

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-anysale
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
volumes: { pgdata: {} }
