package com.anysale.lead.aplication;
import com.anysale.lead.adapters.in.rest.dto.*; import com.anysale.lead.adapters.out.persistence.*; import com.anysale.lead.domain.model.*; import com.anysale.lead.tenant.*;
import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;
@Service public class LeadTaskService {
 private static final Duration RESERVATION=Duration.ofMinutes(15); private static final int MAX_ASSIGNED=5;
 private final LeadTaskJpaRepository tasks; private final LeadJpaRepository leads; private final TenantContext tenants; private final UserIdentityContext users;
 public LeadTaskService(LeadTaskJpaRepository tasks,LeadJpaRepository leads,TenantContext tenants,UserIdentityContext users){this.tasks=tasks;this.leads=leads;this.tenants=tenants;this.users=users;}
 @Transactional public LeadTask create(UUID leadId,LeadTaskCreateRequest r){Lead lead=lead(leadId); LeadTask t=new LeadTask(); t.setLead(lead);t.setTenantId(lead.getTenantId());t.setTitle(r.title().trim());t.setTaskType(r.taskType());t.setPriority(r.priority()==null?"NORMAL":r.priority());t.setDueAt(r.dueAt());t.setNote(trim(r.note()));return tasks.save(t);}
 @Transactional public LeadTask claim(UUID id){String tenant=tenants.tenantId(),user=users.userId();tasks.releaseExpired(tenant,Instant.now());if(tasks.countByTenantIdAndAssignedToAndStatus(tenant,user,"ASSIGNED")>=MAX_ASSIGNED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Task claim limit reached");LeadTask t=task(id,tenant);if(!"OPEN".equals(t.getStatus()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Task is no longer available");Instant now=Instant.now();t.setStatus("ASSIGNED");t.setAssignedTo(user);t.setReservedAt(now);t.setReservationExpiresAt(now.plus(RESERVATION));if(t.getLead().getAssignedTo()==null)t.getLead().setAssignedTo(user);return tasks.save(t);}
 @Transactional public LeadTask release(UUID id){LeadTask t=task(id,tenants.tenantId());owner(t); if("COMPLETED".equals(t.getStatus()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Completed task cannot be released");open(t);return tasks.save(t);}
 @Transactional public LeadTask complete(UUID id,LeadTaskCompleteRequest r){LeadTask t=task(id,tenants.tenantId());owner(t);t.setStatus("COMPLETED");t.setOutcome(r.outcome());t.setNote(trim(r.note()));t.setCompletedAt(Instant.now());t.setReservationExpiresAt(null);return tasks.save(t);}
 @Transactional public LeadTask snooze(UUID id,LeadTaskSnoozeRequest r){LeadTask t=task(id,tenants.tenantId());owner(t);t.setDueAt(r.dueAt());t.setNote(trim(r.note()));open(t);return tasks.save(t);}
 @Transactional public Page<LeadTask> queue(String view,int page,int size){String tenant=tenants.tenantId();tasks.releaseExpired(tenant,Instant.now());Pageable p=PageRequest.of(page,size);return "mine".equalsIgnoreCase(view)?tasks.findMine(tenant,users.userId(),p):tasks.findOpen(tenant,p);}
 @Transactional(readOnly=true) public List<LeadTask> byLead(UUID id){lead(id);return tasks.findByLead_IdOrderByCreatedAtDesc(id);}
 private Lead lead(UUID id){String tenant=tenants.tenantId();Lead l=leads.findByIdWithTags(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Lead not found"));if(!tenant.equals(l.getTenantId()))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Lead not found");return l;}
 private LeadTask task(UUID id,String tenant){return tasks.findScoped(id,tenant).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Task not found"));}
 private void owner(LeadTask t){if(!users.userId().equals(t.getAssignedTo()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Task is assigned to another user");}
 private void open(LeadTask t){t.setStatus("OPEN");t.setAssignedTo(null);t.setReservedAt(null);t.setReservationExpiresAt(null);} private String trim(String v){return v==null||v.isBlank()?null:v.trim();}
}
