spring.application.name=anysale-notification-service

# Porta
server.port=${SERVER_PORT:8081}
lead-service.base-url=${LEAD_SERVICE_BASE_URL:http://localhost:8080}
whatsapp.cloud-api.base-url=${WHATSAPP_GRAPH_API_BASE_URL:https://graph.facebook.com}
whatsapp.cloud-api.version=${WHATSAPP_GRAPH_API_VERSION:v20.0}
whatsapp.cloud-api.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID:}
whatsapp.cloud-api.access-token=${WHATSAPP_ACCESS_TOKEN:}

# Kafka (consumer)
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:notification-service}
spring.kafka.consumer.auto-offset-reset=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.anysale.*

# Actuator
management.endpoints.web.exposure.include=health,info
